version: '3'

services:
  se_db:
    container_name: se-database
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - database.env

volumes:
  postgres_data:
