version: '3'

services:
  sre_api:
    container_name: sre
    restart: always
    build: .
    command: uvicorn app.main:app --reload
    volumes:
      - .:/code
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: pgdb
    ports:
      - 7090:5432
    volumes:
      - ./database/migration/:/tmp/db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: mta

  adminer:
    # restart: on-failure
    image: adminer
    container_name: adminer_mta
    ports:
      - 7080:8080
