version: '3'

services:
  sre_api:
    container_name: sre-api
    restart: always
    build: .
    command: python manage.py run -h 0.0.0.0
    volumes:
      - .:/code
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - sre_db

  sre_db:
    container_name: sre-database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
