version: '3'
services:

  postgres:
    image: postgres
    container_name: pgdb
    ports:
      - "7090:5432"
    volumes:
      - ./migration/:/tmp/db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: mta

  adminer:
    # restart: on-failure
    image: adminer
    container_name: adminer_mta
    ports:
      - "7080:8080"
